import os
import sqlite3
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, Optional
from urllib.parse import quote

from PySide6.QtCore import QUrl
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import QFileDialog, QMessageBox

from services.excel_service import ExcelService
from services.pdf_service import PDFService
from services.print_service import PrintService


DEFAULT_WHATSAPP_MESSAGE = (
    "Dear Customer,\n\n"
    "Please find attached your document.\n\n"
    "Best Regards\n\n"
    "MeWa Automotive"
)


@dataclass
class DocumentPayload:
    title: str
    filename_base: str
    headers: list[str]
    rows: list[list[str]]
    document_number: str = ""
    document_date: str = ""
    currency: str = "USD"
    exchange_rate: str = "1"
    customer_name: str = ""
    customer_code: str = ""
    customer_whatsapp: str = ""
    customer_email: str = ""
    company_name: str = "MeWa Automotive"
    company_info: str = "MeWa Automotive"
    footer_note: str = "Generated by MeWa ERP Professional"
    totals: Dict[str, str] = field(default_factory=dict)


class DocumentExportService:
    def __init__(self, parent=None):
        self.parent = parent
        self.last_pdf_path: Optional[str] = None
        self.last_excel_path: Optional[str] = None

    @staticmethod
    def table_payload(
        *,
        title: str,
        filename_base: str,
        headers: list[str],
        rows: list[list[str]],
        document_number: str = "",
        document_date: str = "",
        currency: str = "USD",
        exchange_rate: str = "1",
        customer_name: str = "",
        customer_code: str = "",
        totals: Optional[Dict[str, str]] = None,
    ) -> DocumentPayload:
        return DocumentPayload(
            title=title,
            filename_base=filename_base,
            headers=headers,
            rows=rows,
            document_number=document_number,
            document_date=document_date,
            currency=currency,
            exchange_rate=exchange_rate,
            customer_name=customer_name,
            customer_code=customer_code,
            totals=totals or {},
        )

    def _resolve_customer_contact(self, payload: DocumentPayload) -> tuple[str, str]:
        whatsapp = str(payload.customer_whatsapp or "").strip()
        email = str(payload.customer_email or "").strip()
        if whatsapp and email:
            return whatsapp, email

        db_path = Path(__file__).resolve().parent.parent / "database" / "mewa.db"
        if not db_path.exists():
            return whatsapp, email

        with sqlite3.connect(str(db_path)) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()

            if not whatsapp or not email:
                code = str(payload.customer_code or "").strip()
                name = str(payload.customer_name or "").strip()
                if code:
                    cursor.execute(
                        "SELECT COALESCE(telefon, '') AS telefon, COALESCE(email, '') AS email FROM cariler WHERE LOWER(COALESCE(cari_kodu, '')) = LOWER(?) LIMIT 1",
                        (code,),
                    )
                    row = cursor.fetchone()
                    if row is not None:
                        whatsapp = whatsapp or str(row["telefon"] or "")
                        email = email or str(row["email"] or "")
                if (not whatsapp or not email) and name:
                    cursor.execute(
                        "SELECT COALESCE(telefon, '') AS telefon, COALESCE(email, '') AS email FROM cariler WHERE LOWER(COALESCE(firma_unvani, '')) = LOWER(?) LIMIT 1",
                        (name,),
                    )
                    row = cursor.fetchone()
                    if row is not None:
                        whatsapp = whatsapp or str(row["telefon"] or "")
                        email = email or str(row["email"] or "")

            if not whatsapp or not email:
                code = str(payload.customer_code or "").strip()
                name = str(payload.customer_name or "").strip()
                if code:
                    cursor.execute(
                        "SELECT COALESCE(whatsapp, ''), COALESCE(email, '') FROM suppliers WHERE LOWER(COALESCE(supplier_code, '')) = LOWER(?) LIMIT 1",
                        (code,),
                    )
                    row = cursor.fetchone()
                    if row is not None:
                        whatsapp = whatsapp or str(row[0] or "")
                        email = email or str(row[1] or "")
                if (not whatsapp or not email) and name:
                    cursor.execute(
                        "SELECT COALESCE(whatsapp, ''), COALESCE(email, '') FROM suppliers WHERE LOWER(COALESCE(company_name, '')) = LOWER(?) LIMIT 1",
                        (name,),
                    )
                    row = cursor.fetchone()
                    if row is not None:
                        whatsapp = whatsapp or str(row[0] or "")
                        email = email or str(row[1] or "")

        return whatsapp.strip(), email.strip()

    @staticmethod
    def _normalize_phone(phone: str) -> str:
        cleaned = "".join(ch for ch in str(phone or "") if ch.isdigit() or ch == "+")
        if cleaned.startswith("+"):
            cleaned = cleaned[1:]
        if cleaned.startswith("00"):
            cleaned = cleaned[2:]
        if cleaned.startswith("0") and len(cleaned) == 11:
            cleaned = "90" + cleaned[1:]
        elif len(cleaned) == 10:
            cleaned = "90" + cleaned
        return cleaned if len(cleaned) >= 10 else ""

    def export_excel(self, payload: DocumentPayload) -> bool:
        default_name = f"{payload.filename_base}.xlsx"
        path, _ = QFileDialog.getSaveFileName(self.parent, "Save Excel", default_name, "Excel Files (*.xlsx)")
        if not path:
            return False
        ok = ExcelService.export_excel_to_path(path, payload.headers, payload.rows, payload.title)
        if ok:
            self.last_excel_path = path
            QMessageBox.information(self.parent, "Success", "Excel exported successfully.")
        else:
            QMessageBox.critical(self.parent, "Error", "Excel export failed.")
        return ok

    def export_pdf(self, payload: DocumentPayload) -> bool:
        default_name = f"{payload.filename_base}.pdf"
        path, _ = QFileDialog.getSaveFileName(self.parent, "Save PDF", default_name, "PDF Files (*.pdf)")
        if not path:
            return False
        ok, err = PDFService.generate_document_pdf_to_path(payload=payload, save_path=path)
        if ok:
            self.last_pdf_path = path
            QMessageBox.information(self.parent, "Success", "PDF generated successfully.")
            return True
        QMessageBox.critical(self.parent, "Error", f"PDF generation failed:\n{err}")
        return False

    def _ensure_temp_pdf(self, payload: DocumentPayload) -> Optional[str]:
        if self.last_pdf_path and os.path.exists(self.last_pdf_path):
            return self.last_pdf_path
        temp = tempfile.NamedTemporaryFile(prefix="mewa_doc_", suffix=".pdf", delete=False)
        temp_path = temp.name
        temp.close()
        ok, _ = PDFService.generate_document_pdf_to_path(payload=payload, save_path=temp_path)
        if not ok:
            return None
        self.last_pdf_path = temp_path
        return temp_path

    def print_document(self, payload: DocumentPayload) -> bool:
        pdf_path = self._ensure_temp_pdf(payload)
        if not pdf_path:
            QMessageBox.critical(self.parent, "Error", "Could not generate PDF for print.")
            return False
        return PrintService.print_pdf_file(self.parent, pdf_path)

    def whatsapp_document(self, payload: DocumentPayload) -> bool:
        pdf_path = self._ensure_temp_pdf(payload)
        if not pdf_path:
            QMessageBox.critical(self.parent, "Error", "Could not generate PDF for WhatsApp.")
            return False

        whatsapp, _ = self._resolve_customer_contact(payload)
        phone = self._normalize_phone(whatsapp)
        if not phone:
            QMessageBox.warning(self.parent, "Warning", "Customer WhatsApp number not found.")
            return False

        text = quote(DEFAULT_WHATSAPP_MESSAGE)
        file_url = quote(pdf_path)

        desktop_url = QUrl(f"whatsapp://send?phone={phone}&text={text}&attachment={file_url}")
        opened = QDesktopServices.openUrl(desktop_url)
        if not opened:
            web_url = QUrl(f"https://web.whatsapp.com/send?phone={phone}&text={text}&attachment={file_url}")
            opened = QDesktopServices.openUrl(web_url)

        if not opened:
            QMessageBox.warning(self.parent, "Warning", "Could not open WhatsApp.")
            return False
        return True

    def email_document(self, payload: DocumentPayload) -> bool:
        pdf_path = self._ensure_temp_pdf(payload)
        if not pdf_path:
            QMessageBox.critical(self.parent, "Error", "Could not generate PDF for email.")
            return False

        _, email = self._resolve_customer_contact(payload)
        subject = quote(f"{payload.title} - {payload.document_number}".strip(" -"))
        body = quote(
            "Dear Customer,\n\n"
            f"Document Number: {payload.document_number}\n"
            f"Customer: {payload.customer_name}\n\n"
            "Please find attached your document.\n\n"
            "Best Regards\n"
            "MeWa Automotive"
        )

        mailto = f"mailto:{email}?subject={subject}&body={body}"
        opened = QDesktopServices.openUrl(QUrl(mailto))
        if not opened:
            QMessageBox.warning(self.parent, "Warning", "Could not open default mail client.")
            return False

        QMessageBox.information(
            self.parent,
            "Info",
            "Mail client opened. Attach the generated PDF from this path:\n"
            f"{pdf_path}",
        )
        return True

    def open_generated_file_folder(self, payload: DocumentPayload) -> bool:
        path = self._ensure_temp_pdf(payload)
        if not path:
            QMessageBox.warning(self.parent, "Warning", "No generated PDF found.")
            return False
        folder = os.path.dirname(path)
        return QDesktopServices.openUrl(QUrl.fromLocalFile(folder))

    def save_as(self, payload: DocumentPayload) -> bool:
        suggested = f"{payload.filename_base}.pdf"
        target, selected_filter = QFileDialog.getSaveFileName(
            self.parent,
            "Save As",
            suggested,
            "PDF Files (*.pdf);;Excel Files (*.xlsx)",
        )
        if not target:
            return False

        ext = Path(target).suffix.lower()
        if ext == ".xlsx" or "Excel" in selected_filter:
            if ext != ".xlsx":
                target = f"{target}.xlsx"
            ok = ExcelService.export_excel_to_path(target, payload.headers, payload.rows, payload.title)
            if ok:
                self.last_excel_path = target
            return ok

        if ext != ".pdf":
            target = f"{target}.pdf"
        ok, _ = PDFService.generate_document_pdf_to_path(payload=payload, save_path=target)
        if ok:
            self.last_pdf_path = target
        return ok


def payload_from_provider(provider: Callable[[], Dict[str, Any]]) -> DocumentPayload:
    data = provider() or {}
    return DocumentPayload(
        title=str(data.get("title") or "Document"),
        filename_base=str(data.get("filename_base") or "document"),
        headers=list(data.get("headers") or []),
        rows=[list(row) for row in (data.get("rows") or [])],
        document_number=str(data.get("document_number") or ""),
        document_date=str(data.get("document_date") or ""),
        currency=str(data.get("currency") or "USD"),
        exchange_rate=str(data.get("exchange_rate") or "1"),
        customer_name=str(data.get("customer_name") or ""),
        customer_code=str(data.get("customer_code") or ""),
        customer_whatsapp=str(data.get("customer_whatsapp") or ""),
        customer_email=str(data.get("customer_email") or ""),
        company_name=str(data.get("company_name") or "MeWa Automotive"),
        company_info=str(data.get("company_info") or "MeWa Automotive"),
        footer_note=str(data.get("footer_note") or "Generated by MeWa ERP Professional"),
        totals=dict(data.get("totals") or {}),
    )
