from datetime import datetime
import os
import traceback
from io import BytesIO
from pathlib import Path
from typing import Any, Sequence

from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QFileDialog, QMessageBox

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from shared.app_assets import get_company_logo_path


class PDFService:
    @staticmethod
    def generate_document_pdf_to_path(payload: Any, save_path: str) -> tuple[bool, str | None]:
        meta_rows = [
            ["Company", str(getattr(payload, "company_name", "MeWa Automotive") or "MeWa Automotive")],
            ["Document Title", str(getattr(payload, "title", "Document") or "Document")],
            ["Customer", str(getattr(payload, "customer_name", "") or "-")],
            ["Customer Code", str(getattr(payload, "customer_code", "") or "-")],
            ["Document Number", str(getattr(payload, "document_number", "") or "-")],
            ["Document Date", str(getattr(payload, "document_date", "") or datetime.now().strftime("%Y-%m-%d"))],
            ["Currency", str(getattr(payload, "currency", "USD") or "USD")],
            ["Exchange Rate", str(getattr(payload, "exchange_rate", "1") or "1")],
        ]

        totals = getattr(payload, "totals", {}) or {}
        total_rows = [[str(k), str(v)] for k, v in totals.items()]

        return PDFService.generate_pdf_to_path(
            headers=list(getattr(payload, "headers", []) or []),
            rows=list(getattr(payload, "rows", []) or []),
            save_path=save_path,
            title=str(getattr(payload, "title", "Document") or "Document"),
            logo_path=None,
            meta_rows=meta_rows,
            total_rows=total_rows,
            footer_note=str(getattr(payload, "footer_note", "Generated by MeWa ERP Professional") or "Generated by MeWa ERP Professional"),
        )

    @staticmethod
    def generate_pdf(
        parent,
        headers: Sequence[str],
        rows: Sequence[Sequence[object]],
        filename: str,
        title: str,
        logo_path: str | None = None,
    ) -> bool:
        try:
            PDFService._register_fonts()
        except Exception as exc:  # pragma: no cover - defensive fallback
            QMessageBox.critical(parent, "Hata", f"PDF motoru başlatılamadı:\n{exc}")
            return False

        save_path, _ = QFileDialog.getSaveFileName(
            parent,
            "PDF Dosyasını Kaydet",
            filename,
            "PDF Dosyaları (*.pdf)",
        )
        if not save_path:
            return False

        success, error_message = PDFService.generate_pdf_to_path(
            headers=headers,
            rows=rows,
            save_path=save_path,
            title=title,
            logo_path=logo_path,
        )
        if not success:
            QMessageBox.critical(parent, "Hata", f"PDF oluşturulurken bir hata oluştu:\n{error_message}")
            return False

        try:
            QMessageBox.information(parent, "Başarılı", "PDF dosyası başarıyla export edildi.")
            return True
        except Exception:
            return True

    @staticmethod
    def generate_pdf_to_path(
        headers: Sequence[str],
        rows: Sequence[Sequence[object]],
        save_path: str,
        title: str,
        logo_path: str | None = None,
        meta_rows: Sequence[Sequence[object]] | None = None,
        total_rows: Sequence[Sequence[object]] | None = None,
        footer_note: str = "Generated by MeWa ERP Professional",
    ) -> tuple[bool, str | None]:
        try:
            PDFService._register_fonts()
            resolved_logo = PDFService._load_logo(logo_path)
            print("Logo:", resolved_logo)
            print("Exists:", os.path.exists(resolved_logo) if isinstance(resolved_logo, str) else False)

            doc = SimpleDocTemplate(
                save_path,
                pagesize=landscape(A4),
                rightMargin=0.4 * inch,
                leftMargin=0.4 * inch,
                topMargin=0.5 * inch,
                bottomMargin=0.6 * inch,
            )
            story = []
            story.extend(PDFService._build_header(title, resolved_logo))

            if meta_rows:
                meta_table = Table(
                    [[str(col) for col in row] for row in meta_rows],
                    colWidths=[1.8 * inch, 4.0 * inch],
                    hAlign="LEFT",
                )
                meta_table.setStyle(
                    TableStyle(
                        [
                            ("FONTNAME", (0, 0), (-1, -1), "DejaVuSans"),
                            ("FONTSIZE", (0, 0), (-1, -1), 8),
                            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#e2e8f0")),
                            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
                            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                            ("LEFTPADDING", (0, 0), (-1, -1), 4),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                        ]
                    )
                )
                story.append(meta_table)
                story.append(Spacer(1, 0.15 * inch))

            if headers:
                table_data = [[str(header) for header in headers]]
                table_data.extend([[str(value) for value in row] for row in rows])
                col_widths = PDFService._compute_column_widths(headers, rows, doc.width)
                table = Table(
                    table_data,
                    repeatRows=1,
                    colWidths=col_widths,
                    hAlign="LEFT",
                )
                table.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                            ("FONTNAME", (0, 0), (-1, 0), "DejaVuSans-Bold"),
                            ("FONTNAME", (0, 1), (-1, -1), "DejaVuSans"),
                            ("FONTSIZE", (0, 0), (-1, -1), 8),
                            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
                            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                            ("TOPPADDING", (0, 0), (-1, -1), 4),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                            ("LEFTPADDING", (0, 0), (-1, -1), 4),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                        ]
                    )
                )
                story.append(table)
            else:
                story.append(Paragraph("Kayıt bulunamadı.", PDFService._body_style()))

            if total_rows:
                story.append(Spacer(1, 0.16 * inch))
                totals_table = Table(
                    [[str(col) for col in row] for row in total_rows],
                    colWidths=[2.2 * inch, 2.0 * inch],
                    hAlign="RIGHT",
                )
                totals_table.setStyle(
                    TableStyle(
                        [
                            ("FONTNAME", (0, 0), (-1, -1), "DejaVuSans-Bold"),
                            ("FONTSIZE", (0, 0), (-1, -1), 8),
                            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#94a3b8")),
                            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f8fafc")),
                            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                        ]
                    )
                )
                story.append(totals_table)

            story.extend(PDFService._build_footer(len(rows), footer_note))
            doc.build(story, onFirstPage=PDFService._draw_canvas, onLaterPages=PDFService._draw_canvas)
            return True, None
        except Exception as exc:
            tb = traceback.format_exc()
            print(tb)
            return False, f"{exc}\n{tb}"

    @staticmethod
    def _register_fonts() -> None:
        try:
            pdfmetrics.registerFont(TTFont("DejaVuSans", "c:/Windows/Fonts/arial.ttf"))
            pdfmetrics.registerFont(TTFont("DejaVuSans-Bold", "c:/Windows/Fonts/arialbd.ttf"))
        except Exception:
            pdfmetrics.registerFont(TTFont("DejaVuSans", "DejaVuSans.ttf"))
            pdfmetrics.registerFont(TTFont("DejaVuSans-Bold", "DejaVuSans-Bold.ttf"))

    @staticmethod
    def _build_header(title: str, logo_source):
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Title"],
            fontName="DejaVuSans-Bold",
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=8,
        )
        meta_style = ParagraphStyle(
            "MetaStyle",
            parent=styles["BodyText"],
            fontName="DejaVuSans",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#475569"),
            spaceAfter=4,
        )

        elements = []
        if isinstance(logo_source, str):
            elements.append(Image(logo_source, width=1.0 * inch, height=1.0 * inch, hAlign="LEFT"))
        elif isinstance(logo_source, (bytes, bytearray)):
            elements.append(Image(BytesIO(logo_source), width=1.0 * inch, height=1.0 * inch, hAlign="LEFT"))
        elements.append(Paragraph(title, title_style))
        elements.append(Paragraph(datetime.now().strftime("Tarih: %d.%m.%Y"), meta_style))
        elements.append(Paragraph(datetime.now().strftime("Saat: %H:%M"), meta_style))
        elements.append(Spacer(1, 0.2 * inch))
        elements.append(Paragraph("─" * 60, ParagraphStyle("Divider", parent=styles["BodyText"], fontName="DejaVuSans", fontSize=10, textColor=colors.HexColor("#cbd5e1"))))
        elements.append(Spacer(1, 0.2 * inch))
        return elements

    @staticmethod
    def _build_footer(total_records: int, footer_note: str):
        styles = getSampleStyleSheet()
        footer_style = ParagraphStyle(
            "FooterStyle",
            parent=styles["BodyText"],
            fontName="DejaVuSans",
            fontSize=8,
            leading=10,
            textColor=colors.HexColor("#64748b"),
        )
        return [
            Spacer(1, 0.3 * inch),
            Paragraph(f"Toplam Kayıt: {total_records}", footer_style),
            Paragraph(footer_note, footer_style),
        ]

    @staticmethod
    def _body_style() -> ParagraphStyle:
        styles = getSampleStyleSheet()
        return ParagraphStyle(
            "Body",
            parent=styles["BodyText"],
            fontName="DejaVuSans",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334155"),
        )

    @staticmethod
    def _draw_canvas(canvas, doc) -> None:
        canvas.saveState()
        canvas.setFont("DejaVuSans", 8)
        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.drawString(0.45 * inch, 0.3 * inch, f"Sayfa {canvas.getPageNumber()}")
        canvas.drawRightString(landscape(A4)[0] - 0.45 * inch, 0.3 * inch, "MeWa ERP Professional")
        canvas.restoreState()

    @staticmethod
    def _compute_column_widths(headers: Sequence[str], rows: Sequence[Sequence[object]], page_width: float):
        if not headers:
            return []

        max_lengths = []
        for index, header in enumerate(headers):
            longest = len(str(header))
            for row in rows:
                value = str(row[index]) if index < len(row) else ""
                longest = max(longest, len(value))
            max_lengths.append(longest)

        total_width = sum(max(80, value * 7) for value in max_lengths)
        available_width = page_width - 0.8 * inch
        if total_width <= available_width:
            return [max(80, value * 7) for value in max_lengths]

        scale = available_width / total_width
        return [max(70, int(value * scale)) for value in [max(80, value * 7) for value in max_lengths]]

    @staticmethod
    def _load_logo(logo_path: str | None):
        if logo_path:
            path = Path(logo_path)
            if path.exists():
                pixmap = QPixmap(str(path))
                if not pixmap.isNull():
                    return str(path)

        candidate = get_company_logo_path()
        if candidate.exists():
            pixmap = QPixmap(str(candidate))
            if not pixmap.isNull():
                return str(candidate)
        return None
