from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class UITheme:
    BG_APP: str = "#0b1220"
    BG_SURFACE: str = "#0f172a"
    BG_SURFACE_ALT: str = "#111827"
    BG_INPUT: str = "#0f1324"
    BORDER: str = "#334155"
    BORDER_SOFT: str = "#475569"
    TEXT_PRIMARY: str = "#e2e8f0"
    TEXT_STRONG: str = "#f8fafc"
    TEXT_MUTED: str = "#94a3b8"
    FOCUS: str = "#60a5fa"

    BTN_PREVIEW: str = "#1e293b"
    BTN_PREVIEW_HOVER: str = "#334155"
    BTN_PREVIEW_PRESS: str = "#172033"

    BTN_SAVE: str = "#14532d"
    BTN_SAVE_HOVER: str = "#166534"
    BTN_SAVE_PRESS: str = "#0f3f23"

    BTN_SAVE_CLOSE: str = "#1d4ed8"
    BTN_SAVE_CLOSE_HOVER: str = "#2563eb"
    BTN_SAVE_CLOSE_PRESS: str = "#1e40af"

    BTN_CANCEL: str = "#991b1b"
    BTN_CANCEL_HOVER: str = "#b91c1c"
    BTN_CANCEL_PRESS: str = "#7f1d1d"

    BUTTON_HEIGHT: int = 44
    BUTTON_RADIUS: int = 11
    BUTTON_PADDING_X: int = 16


THEME = UITheme()


def global_stylesheet() -> str:
    t = THEME
    return (
        "QWidget {"
        f"background:{t.BG_APP};"
        f"color:{t.TEXT_PRIMARY};"
        "font-size:13px;"
        "}"
        "QDialog, QMainWindow {"
        f"background:{t.BG_APP};"
        "}"
        "QFrame[card='true'] {"
        f"background:{t.BG_SURFACE};"
        f"border:1px solid {t.BORDER};"
        "border-radius:12px;"
        "}"
        "QLabel[role='title'] {"
        "font-size:24px;"
        "font-weight:700;"
        f"color:{t.TEXT_STRONG};"
        "padding:6px 0;"
        "}"
        "QLabel[role='sectionTitle'] {"
        "font-size:15px;"
        "font-weight:600;"
        f"color:{t.TEXT_STRONG};"
        "}"
        "QLabel[role='muted'] {"
        f"color:{t.TEXT_MUTED};"
        "font-size:12px;"
        "}"
        "QLineEdit,QComboBox,QDateEdit,QTextEdit,QDoubleSpinBox,QSpinBox {"
        f"background:{t.BG_INPUT};"
        f"color:{t.TEXT_PRIMARY};"
        f"border:1px solid {t.BORDER};"
        "border-radius:8px;"
        "padding:8px;"
        "selection-background-color:#1e3a8a;"
        "selection-color:#ffffff;"
        "}"
        "QLineEdit:focus,QComboBox:focus,QDateEdit:focus,QTextEdit:focus,QDoubleSpinBox:focus,QSpinBox:focus {"
        f"border:1px solid {t.FOCUS};"
        "background:#111827;"
        "}"
        "QTableWidget,QTreeWidget,QTableView {"
        f"background:{t.BG_SURFACE_ALT};"
        "alternate-background-color:#0f172a;"
        f"color:{t.TEXT_PRIMARY};"
        f"border:1px solid {t.BORDER};"
        "gridline-color:#1f2937;"
        "}"
        "QHeaderView::section {"
        "background:#1f2937;"
        "color:#e5e7eb;"
        "padding:8px 6px;"
        "border:1px solid #111827;"
        "}"
        "QTableWidget::item:selected,QTreeWidget::item:selected,QTableView::item:selected {"
        "background:#1d4ed8;"
        "color:#ffffff;"
        "}"
        "QGroupBox {"
        f"color:{t.TEXT_PRIMARY};"
        f"border:1px solid {t.BORDER};"
        "border-radius:10px;"
        "margin-top:6px;"
        "font-weight:600;"
        "}"
        "QGroupBox::title {"
        "subcontrol-origin: margin;"
        "left:10px;"
        "padding:0 4px;"
        "}"
        "QPushButton {"
        f"min-height:{t.BUTTON_HEIGHT}px;"
        f"padding:8px {t.BUTTON_PADDING_X}px;"
        f"border:1px solid {t.BORDER_SOFT};"
        f"border-radius:{t.BUTTON_RADIUS}px;"
        "font-weight:600;"
        "}"
        "QPushButton:disabled {"
        "background:#1f2937;"
        "color:#64748b;"
        "border:1px solid #334155;"
        "}"
        "QPushButton[role='preview'] {"
        f"background:{t.BTN_PREVIEW};"
        "color:#e2e8f0;"
        "}"
        "QPushButton[role='preview']:hover {"
        f"background:{t.BTN_PREVIEW_HOVER};"
        "}"
        "QPushButton[role='preview']:pressed {"
        f"background:{t.BTN_PREVIEW_PRESS};"
        "}"
        "QPushButton[role='save'] {"
        f"background:{t.BTN_SAVE};"
        "color:#ecfdf5;"
        "border:1px solid #22c55e;"
        "}"
        "QPushButton[role='save']:hover {"
        f"background:{t.BTN_SAVE_HOVER};"
        "}"
        "QPushButton[role='save']:pressed {"
        f"background:{t.BTN_SAVE_PRESS};"
        "}"
        "QPushButton[role='saveClose'] {"
        f"background:{t.BTN_SAVE_CLOSE};"
        "color:#eff6ff;"
        "border:1px solid #60a5fa;"
        "}"
        "QPushButton[role='saveClose']:hover {"
        f"background:{t.BTN_SAVE_CLOSE_HOVER};"
        "}"
        "QPushButton[role='saveClose']:pressed {"
        f"background:{t.BTN_SAVE_CLOSE_PRESS};"
        "}"
        "QPushButton[role='cancel'] {"
        f"background:{t.BTN_CANCEL};"
        "color:#fef2f2;"
        "border:1px solid #ef4444;"
        "}"
        "QPushButton[role='cancel']:hover {"
        f"background:{t.BTN_CANCEL_HOVER};"
        "}"
        "QPushButton[role='cancel']:pressed {"
        f"background:{t.BTN_CANCEL_PRESS};"
        "}"
        "QToolBar[role='flat'] {"
        f"background:{t.BG_SURFACE};"
        f"border:1px solid {t.BORDER};"
        "border-radius:10px;"
        "padding:6px;"
        "spacing:8px;"
        "}"
    )


def apply_global_theme(app) -> None:
    app.setStyleSheet(global_stylesheet())
